name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Emscripten
      - name: Set up Emscripten
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y cmake python3
          
          # Install Emscripten SDK
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          
      # Compile C++ code to WebAssembly
      - name: Compile C++ code to WebAssembly
        run: |
          source ./emsdk_env.sh # Ensure Emscripten environment is set
          emcc your_cpp_file.cpp -o output.html # Replace with your actual C++ file

      # Setup Pages (after compiling)
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload the compiled artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output.html' # Replace with your compiled files

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
